### ISSUE TITLE
proper implementation for `scala.compiler.additionalParams`

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [random-maven/scalor-maven-plugin#12]
see #10

**Comment by Andrei-Pozolotin** [comment]
@m50d 
1. please verify fix in fresh 1.4.0:
https://bintray.com/random-maven/maven/scalor-maven-plugin_2.12
2. working project example for reference:
https://github.com/random-maven/scalor-maven-plugin/blob/develop/demo/pom.xml#L240
https://github.com/random-maven/scalor-maven-plugin/blob/develop/demo/pom.xml#L316
3. a way to test is:
* delete `${project.basedir}/.settings/...`
* issue from menu: `${project} -> Maven -> Update Project ...`

**Comment by m50d** [comment]
Seems fixed in 1.4.0, many thanks.

**Comment by Andrei-Pozolotin** [comment]
resolved https://github.com/random-maven/scalor-maven-plugin/releases/tag/1.4.0.20180329174003
