### ISSUE TITLE
use separate source regex for compile and scaladoc

### ISSUE THREAD

**Issue by m50d** [random-maven/scalor-maven-plugin#13]
Config to exclude files from scaladoc?
---
Could a config option to exclude specific source files from the scaladoc goal be added (or did I miss one that was there already)? Scaladoc doesn't seem to process files that use kind-projector correctly, so when using the maven-scala-plugin I used to exclude those files.

Thanks as always.

**Comment by Andrei-Pozolotin** [comment]
try separate config for scaladoc execution
https://random-maven.github.io/scalor-maven-plugin/2.12/scaladoc-main-mojo.html#zincRegexAnyScala
```
<executions>
   <execution>
      <goals>
         <goal>compile-main</goal>
      </goals>
   </execution>
   <execution>
      <goals>
         <goal>scaladoc-main</goal>
      </goals>
      <configuration>
         <zincRegexAnyScala>...</zincRegexAnyScala>
      </configuration>
   </execution>
</executions>
```

**Comment by m50d** [comment]
Changing that setting doesn't seem to do anything - all scala files are still passed to the scaladoc invocation, even if I set the regex to something completely bogus. [Searching this repository](https://github.com/random-maven/scalor-maven-plugin/search?p=1&q=zincRegexAnyScala&type=&utf8=%E2%9C%93) it doesn't look like that config is actually used in the plugin code at all?

**Comment by Andrei-Pozolotin** [comment]
ok, thinking

**Comment by Andrei-Pozolotin** [comment]
1. now using separate regex include/exclude for relevant goals
```
<formatRegexScalaInclude>...</formatRegexScalaInclude>
<formatRegexScalaExclude>...</formatRegexScalaExclude>

<compileRegexScalaInclude>...</compileRegexScalaInclude>
<compileRegexScalaExclude>...</compileRegexScalaExclude>

<scaladocRegexScalaInclude>...</scaladocRegexScalaInclude>
<scaladocRegexScalaExclude>...</scaladocRegexScalaExclude>
```
i.e.
https://github.com/random-maven/scalor-maven-plugin/blob/develop/src/main/scala/com/carrotgarden/maven/scalor/document/Scaladoc.scala#L54

2. please try fresh 1.4.0
https://bintray.com/random-maven/maven/scalor-maven-plugin_2.12

**Comment by m50d** [comment]
Hi, the exclude config still doesn't seem to do anything. E.g. even if I set `<scaladocRegexScalaExclude>.*</scaladocRegexScalaExclude>` it's still passing all my source files into Scaladoc:

````
[INFO] [scaladoc-macro] [DBUG] Calling Scaladoc with arguments:
	-d
	C:\Users\md401\eclipse-workspace\tierney-aggregator\core\target\site\scaladoc-main
	-bootclasspath
	C:\Users\md401\.m2\repository\org\scala-lang\scala-library\2.12.4\scala-library-2.12.4.jar
	-classpath
	C:\Users\md401\.m2\repository\org\typelevel\cats-free_2.12\1.0.0-RC2\cats-free_2.12-1.0.0-RC2.jar;C:\Users\md401\.m2\repository\org\typelevel\cats-macros_2.12\1.0.0-RC2\cats-macros_2.12-1.0.0-RC2.jar;C:\Users\md401\.m2\repository\org\typelevel\cats-core_2.12\1.0.0-RC2\cats-core_2.12-1.0.0-RC2.jar;C:\Users\md401\.m2\repository\org\typelevel\cats-kernel_2.12\1.0.0-RC2\cats-kernel_2.12-1.0.0-RC2.jar;C:\Users\md401\.m2\repository\org\typelevel\machinist_2.12\0.6.2\machinist_2.12-0.6.2.jar;C:\Users\md401\.m2\repository\org\scala-lang\scala-reflect\2.12.4\scala-reflect-2.12.4.jar;C:\Users\md401\.m2\repository\org\typelevel\kittens_2.12\1.0.0-RC1\kittens_2.12-1.0.0-RC1.jar;C:\Users\md401\.m2\repository\org\typelevel\alleycats-core_2.12\1.0.0-RC1\alleycats-core_2.12-1.0.0-RC1.jar;C:\Users\md401\.m2\repository\org\typelevel\export-hook_2.12\1.2.0\export-hook_2.12-1.2.0.jar;C:\Users\md401\.m2\repository\com\chuusai\shapeless_2.12\2.3.2\shapeless_2.12-2.3.2.jar;C:\Users\md401\.m2\repository\org\typelevel\macro-compat_2.12\1.1.1\macro-compat_2.12-1.1.1.jar;C:\Users\md401\.m2\repository\org\scala-lang\scala-compiler\2.12.4\scala-compiler-2.12.4.jar;C:\Users\md401\.m2\repository\org\scala-lang\modules\scala-xml_2.12\1.0.6\scala-xml_2.12-1.0.6.jar;C:\Users\md401\.m2\repository\org\scala-lang\scala-reflect\2.12.4\scala-reflect-2.12.4.jar
model contains 1 documentable templates
[INFO] [scaladoc] Invoking goal: scaladoc-main
[INFO] [scaladoc-main] Generating Scaladoc: C:\Users\md401\eclipse-workspace\tierney-aggregator\core\target\site\scaladoc-main
[INFO] [scaladoc-main] Invoking Zinc compiler: Scalor [60d975382eaf68ec152bc305f82611e8]: 2.12.4
[INFO] [scaladoc-main] [DBUG] Returning already retrieved and compiled bridge: C:\Users\md401\.m2\repository\org\scala-sbt\compiler-bridge_2.12\1.1.1\compiler-bridge_2.12-1.1.1.jar.
[INFO] [scaladoc-main] [DBUG] Calling Scaladoc with arguments:
	-d
	C:\Users\md401\eclipse-workspace\tierney-aggregator\core\target\site\scaladoc-main
	-bootclasspath
	C:\Users\md401\.m2\repository\org\scala-lang\scala-library\2.12.4\scala-library-2.12.4.jar
	-classpath
	C:\Users\md401\eclipse-workspace\tierney-aggregator\core\target\classes;C:\Users\md401\.m2\repository\org\typelevel\cats-free_2.12\1.0.0-RC2\cats-free_2.12-1.0.0-RC2.jar;C:\Users\md401\.m2\repository\org\typelevel\cats-macros_2.12\1.0.0-RC2\cats-macros_2.12-1.0.0-RC2.jar;C:\Users\md401\.m2\repository\org\typelevel\cats-core_2.12\1.0.0-RC2\cats-core_2.12-1.0.0-RC2.jar;C:\Users\md401\.m2\repository\org\typelevel\cats-kernel_2.12\1.0.0-RC2\cats-kernel_2.12-1.0.0-RC2.jar;C:\Users\md401\.m2\repository\org\typelevel\machinist_2.12\0.6.2\machinist_2.12-0.6.2.jar;C:\Users\md401\.m2\repository\org\scala-lang\scala-reflect\2.12.4\scala-reflect-2.12.4.jar;C:\Users\md401\.m2\repository\org\typelevel\kittens_2.12\1.0.0-RC1\kittens_2.12-1.0.0-RC1.jar;C:\Users\md401\.m2\repository\org\typelevel\alleycats-core_2.12\1.0.0-RC1\alleycats-core_2.12-1.0.0-RC1.jar;C:\Users\md401\.m2\repository\org\typelevel\export-hook_2.12\1.2.0\export-hook_2.12-1.2.0.jar;C:\Users\md401\.m2\repository\com\chuusai\shapeless_2.12\2.3.2\shapeless_2.12-2.3.2.jar;C:\Users\md401\.m2\repository\org\typelevel\macro-compat_2.12\1.1.1\macro-compat_2.12-1.1.1.jar;C:\Users\md401\.m2\repository\org\scala-lang\scala-compiler\2.12.4\scala-compiler-2.12.4.jar;C:\Users\md401\.m2\repository\org\scala-lang\modules\scala-xml_2.12\1.0.6\scala-xml_2.12-1.0.6.jar;C:\Users\md401\.m2\repository\org\scala-lang\scala-reflect\2.12.4\scala-reflect-2.12.4.jar
	C:\Users\md401\eclipse-workspace\tierney-aggregator\core\src\main\scala\tierney\core\EitherKSupport.scala
	C:\Users\md401\eclipse-workspace\tierney-aggregator\core\src\main\scala\tierney\core\FunctorK.scala
	C:\Users\md401\eclipse-workspace\tierney-aggregator\core\src\main\scala\tierney\core\FunctorKK.scala
	C:\Users\md401\eclipse-workspace\tierney-aggregator\core\src\main\scala\tierney\core\LazyFunctionK.scala
	C:\Users\md401\eclipse-workspace\tierney-aggregator\core\src\main\scala\tierney\core\LazyFunctionKK.scala
	C:\Users\md401\eclipse-workspace\tierney-aggregator\core\src\main\scala\tierney\core\package.scala
[ERROR] [scaladoc-main] [FAIL] [Error] C:\Users\md401\eclipse-workspace\tierney-aggregator\core\src\main\scala\tierney\core\EitherKSupport.scala:10: not found: type ?
...
````

**Comment by Andrei-Pozolotin** [comment]
1. can not reproduce, here is integration test:

https://github.com/random-maven/scalor-maven-plugin/tree/develop/src/it/test-any/src/main/scala/any

https://github.com/random-maven/scalor-maven-plugin/blob/develop/src/it/test-any/pom.xml#L75

https://github.com/random-maven/scalor-maven-plugin/blob/develop/src/it/test-any/verify.groovy#L20

2. which builds fine on windows:

a) `compile-main` includes all by default:
https://ci.appveyor.com/project/random-maven/scalor-maven-plugin/build/57/job/wh3rrapd543nsods#L4481

```
4481[INFO] [INFO] [compile-main] Sources list:
4482[INFO]    C:\projects\scalor-maven-plugin\cross\2.12\target\it\test-any\src\main\scala\any\Main.scala
4483[INFO]    C:\projects\scalor-maven-plugin\cross\2.12\target\it\test-any\src\main\scala\any\Skip.scala
```

b) `scaladoc-main` excludes as configured in `pom.xml`:
https://ci.appveyor.com/project/random-maven/scalor-maven-plugin/build/57/job/wh3rrapd543nsods#L4603
```
4604[INFO] [INFO] [scaladoc-main] Sources list:
4605[INFO]    C:\projects\scalor-maven-plugin\cross\2.12\target\it\test-any\src\main\scala\any\Main.scala
```

**Comment by Andrei-Pozolotin** [comment]
resolved https://github.com/random-maven/scalor-maven-plugin/releases/tag/1.4.0.20180329174003

**Comment by m50d** [comment]
Can't reproduce the fix using 1.4.0.20180329174003, but I can't see the "Sources list:" line by setting `<zincLogSourcesList>true</zincLogSourcesList>` either. Something seems very weird.

https://github.com/m50d/tierney/pull/35 is where I'm trying to use this, the travis build https://travis-ci.org/m50d/tierney/builds/360624711 is showing the same behaviour I'm seeing. Can you see what I'm doing wrong?

**Comment by Andrei-Pozolotin** [comment]
1. checking

2. `zincLogSourcesList` is enabled and present in `core`
https://travis-ci.org/m50d/tierney/builds/360624711#L4780
https://travis-ci.org/m50d/tierney/builds/360624711#L3746
and not enabled and missing in `free`, or did you mean something else?

3. `scaladocRegexScalaExclude` basic mistake was: 
* need to use `full path` regex match pattern
* NOT just file name match
```xml
<scaladocRegexScalaExclude>.+(EitherKSupport|FunctionKK|FunctorKK|FunctorK|LazyFunctionKK|FixKTest|package)[.]scala</scaladocRegexScalaExclude>
<scaladocRegexScalaExclude>.+(FreeApplicativeSupport|FreeSupport|TierneyFree|TierneyFreeTest|Programs|Github|ParallelApplicativeTest|package)[.]scala</scaladocRegexScalaExclude>

```

4. builds fine now
https://travis-ci.org/m50d/tierney/builds/361252354

5. given amount of exclude, scaladoc becomes meaningliness
* lets work with `zinc` /  `kind-projector` people to resolve underlying scaladoc issue

**Comment by m50d** [comment]
Hmm, looks like I misread the logs and the exclude in tierney-core was working? Thanks for the fix.

Addressing the scaladoc issue is on my radar, but getting some sort of working scaladoc jar was the important thing as having a doc jar is a requirement for releasing to maven central.

**Comment by m50d** [comment]
Build passed before merging but now can't resolve that release of the plugin? https://travis-ci.org/m50d/tierney/builds/361796725?utm_source=github_status&utm_medium=notification

**Comment by Andrei-Pozolotin** [comment]
need to keep updating to live version, they change after each commit and by `cron`
https://bintray.com/random-maven/maven/scalor-maven-plugin_2.12
https://travis-ci.org/random-maven/scalor-maven-plugin/builds

**Comment by m50d** [comment]
Thanks, working now.

**Comment by Andrei-Pozolotin** [comment]
resolved by https://github.com/random-maven/scalor-maven-plugin/releases/tag/1.4.1.20180403213227
