### ISSUE TITLE
use constant default options for JavaC and ScalaC

### ISSUE THREAD

**Issue by m50d** [random-maven/scalor-maven-plugin#14]
If maven.compiler.target not set, compiler is invoked with `-target jvm-${maven.compiler.target}` 

Minor but it makes the error less clear than it should be, since one only sees the error message from the compiler itself. (I think I also saw an error in Eclipse from that string being used somewhere)

**Comment by Andrei-Pozolotin** [comment]
ok, thinking

**Comment by Andrei-Pozolotin** [comment]
minimal-surprise solution is to use constants; see if you like this better:

https://github.com/random-maven/scalor-maven-plugin/blob/develop/src/main/scala/com/carrotgarden/maven/scalor/zinc/Params.scala#L102

https://github.com/random-maven/scalor-maven-plugin/blob/develop/src/main/scala/com/carrotgarden/maven/scalor/zinc/Params.scala#L155

**Comment by m50d** [comment]
Sounds good to me.

**Comment by Andrei-Pozolotin** [comment]
resolved https://github.com/random-maven/scalor-maven-plugin/releases/tag/1.4.0.20180329174003
