### ISSUE TITLE
Better advanced usage link

### ISSUE THREAD

**Issue by hunterpayne** [random-maven/scalor-maven-plugin#25]
The link in the readme just points to the main github page of the plugin.  I've written a library called Terra that uses your plugin to do a cross build of 2.11, 2.12, and 2.13 plus JS and native support where its possible.  Its a pretty good example of an advanced usage of your plugin.  https://github.com/hunterpayne/terra

**Comment by hunterpayne** [comment]
Here is another good example I wrote.  https://github.com/hunterpayne/eprop

**Comment by Andrei-Pozolotin** [comment]
resolved in https://github.com/random-maven/scalor-maven-plugin/releases/tag/1.5.0.20190502185130
