### ISSUE TITLE
SNAPSHOT cross release for Scala 2.11 & Scala 2.13?

### ISSUE THREAD

**Issue by tribbloid** [random-maven/scalor-maven-plugin#3]
Just a suggestion from what I have read so far :

If you have a CI server, you should consider adding publishing artifact for other Scala versions into your build pipeline, as your plugin is already designed for cross-build

Many enterprise software in Scala are written for Apache Spark 1.6 & 2.x, which haven't upgraded to Scala 2.12 yet.

**Comment by Andrei-Pozolotin** [comment]
you are right, but this project is a different case:

1) this plugin must interact with Scala IDE, which uses fixed Scala epoch, 
so only plugin 2.12 makes sense in IDE 4.7, and only plugin 2.13 will make sense in IDE 4.8

2) cross build of the target project (not plugin) is done via `compile-bridge`, 
and does not depend on the plugin Scala version binding, see:
https://github.com/random-maven/scalor-maven-plugin#version-mapping

3) yes, when IDE 4.8 / Scala 2.13 becomes available
we will publish plugin 2.13

**Comment by tribbloid** [comment]
I see.
I'm using IntelliJ Scala plugin, and I believe this is most people are using now.

**Comment by Andrei-Pozolotin** [comment]
Then you will not be interested in this plugin - closing.
