### ISSUE TITLE
definePluginList should be optional

### ISSUE THREAD

**Issue by slandelle** [random-maven/scalor-maven-plugin#7]
Most projects won't compile any ScalaJs nor macros.
It would be convenient that the `<definePluginList>` configuration block isn't mandatory.
Currently, it needs to be defined, even if it's empty (`<definePluginList></definePluginList>`) otherwise the plugin crashes with a NPE.

**Comment by slandelle** [comment]
@Andrei-Pozolotin I hope you don't mind all those feature requests, I thought some feedback might be helpful. Thanks a lot for this great work!!!

**Comment by Andrei-Pozolotin** [comment]
1. ok, fixing
2. your feedback is good, please keep sharing

**Comment by Andrei-Pozolotin** [comment]
1. here is logic:
https://github.com/random-maven/scalor-maven-plugin/blob/develop/src/main/scala/com/carrotgarden/maven/scalor/base/Params.scala#L303

2. try 1.2.4
https://bintray.com/random-maven/maven/scalor-maven-plugin_2.12

**Comment by slandelle** [comment]
@Andrei-Pozolotin I still have the NPE after upgrading to 1.2.4.20180216045618:

<img width="776" alt="capture d ecran 2018-02-16 a 09 37 22" src="https://user-images.githubusercontent.com/849197/36299416-19a21e22-12fd-11e8-9792-f73e4bba6c01.png">

**Comment by Andrei-Pozolotin** [comment]
1. can not reproduce, need a trace

2. try to activate Eclipse Error Log view, see if trace is there
https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Freference%2Fref-error_log_view.htm

3. try to activate Eclipse Maven Console, see if trace is there
https://www.ibm.com/support/knowledgecenter/SS8PJ7_9.1.0/com.ibm.etools.maven.doc/topics/troubleshooting.html

4. try to attach here zip of fresh Eclipse session log with error trace
```
[workspace]/.metadata/.log
```
5. ensure full trace is in fact enabled for Eclipse JVM
https://stackoverflow.com/questions/2411487/nullpointerexception-in-java-with-no-stacktrace
```
-XX:-OmitStackTraceInFastThrow
```

**Comment by slandelle** [comment]
Here are the logs with the NPE stacktrace.

[log.zip](https://github.com/random-maven/scalor-maven-plugin/files/1731463/log.zip)

Please let me know if you need a pom.xml (I'll have to clean up mine).

**Comment by slandelle** [comment]
build section looks like this:

```xml
<build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>3.7.0</version>
			<configuration>
				<skip>true</skip>
				<skipMain>true</skipMain>
			</configuration>
		</plugin>

		<plugin>
			<groupId>com.carrotgarden.maven</groupId>
			<artifactId>scalor-maven-plugin_2.12</artifactId>
			<version>1.2.4.20180216045618</version>
			<configuration>
				<!-- Extra logging for demonstration purposes. -->
				<zincLogSourcesList>true</zincLogSourcesList>
				<zincLogProjectClassPath>true</zincLogProjectClassPath>
				<zincLogCompilerClassPath>true</zincLogCompilerClassPath>
				<zincLogCompilerPluginList>true</zincLogCompilerPluginList>
				<!-- <linkerLogRuntime>true</linkerLogRuntime> -->
				<!-- <linkerLogOptions>true</linkerLogOptions> -->
				<!-- <linkerLogClassPath>true</linkerLogClassPath> -->
				<linkerLogBuildStats>true</linkerLogBuildStats>
				<linkerLogUpdateResult>true</linkerLogUpdateResult>
				<envconfLogConfig>true</envconfLogConfig>
				<!-- <eclipseLogBuildParticipant>true</eclipseLogBuildParticipant> -->
				<defineBridge>
					<dependency>
						<groupId>org.scala-sbt</groupId>
						<artifactId>compiler-bridge_${version.scala.major}</artifactId>
						<version>${version.scala.zinc}</version>
					</dependency>
				</defineBridge>
				<defineCompiler>
					<dependency>
						<groupId>org.scala-lang</groupId>
						<artifactId>scala-compiler</artifactId>
						<version>${version.scala.release}</version>
					</dependency>
				</defineCompiler>
				<!-- <definePluginList></definePluginList> uncomment to remove NPE--> 
			</configuration>
			<executions>
				<execution>
					<goals>
						<goal>eclipse-config</goal>
						<goal>eclipse-restart</goal>
						<goal>eclipse-prescomp</goal>
						<goal>register-main</goal>
						<goal>register-test</goal>
						<goal>compile-main</goal>
						<goal>compile-test</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
```

**Comment by Andrei-Pozolotin** [comment]
ok, fixing

**Comment by Andrei-Pozolotin** [comment]
please try again 1.2.4
https://bintray.com/random-maven/maven/scalor-maven-plugin_2.12

**Comment by slandelle** [comment]
Looking good now, thanks a lot!
