### ISSUE TITLE
defineCompiler should be optional

### ISSUE THREAD

**Issue by slandelle** [random-maven/scalor-maven-plugin#8]
I guess some people might have to configure a specific compiler version, but by default, the plugin should be able to infer the proper scala-compiler artifact (groupId and artifactId are well known and version can be inferred from the scala-library jar that's in the project dependency tree).

(that's what I do in the gatling-maven-plugin)

**Comment by Andrei-Pozolotin** [comment]
see #7

**Comment by slandelle** [comment]
Looking good as of 1.2.4.20180217070934
