### ISSUE TITLE
defineBridge should be optional

### ISSUE THREAD

**Issue by slandelle** [random-maven/scalor-maven-plugin#9]
It would be convenient to have a default value, most likely hardcoded in the plugin.

**Comment by Andrei-Pozolotin** [comment]
see #7

**Comment by Andrei-Pozolotin** [comment]
1. thank you for the idea

2. released, please verify and close
https://repo1.maven.org/maven2/com/carrotgarden/maven/scalor-maven-plugin_2.12/

**Comment by slandelle** [comment]
Just tested 1.3.0.20180218205359, works like a charm! Thanks a lot!
